name: build

on:
  push:
    branches: [ staging ]
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.201'

    - name: Install YouTubeArchiverServer
      run: dotnet tool install -g YouTubeArchiverServer

    - name: Build
      run: make
    
    - name: Commit files
      id: commit_step
      run: |
        cd output/web
        git add .
        if git diff-index --quiet HEAD --; then
            echo "##[set-output name=has_commits;]false"
        else
            echo "##[set-output name=has_commits;]true"
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -m "Web updates." -a
        fi

    - name: Push changes
      if: steps.commit_step.outputs.has_commits == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd output/web
        remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git push "${remote_repo}" HEAD:master;
